Repository elastic/apm-nodejs-http-client, pull requests merged in 2018-12, with the labels that each got.

#37 test: add test for circular references
  test/edge-cases.js
  test/lib/utils.js
Labels: [zube]: In Review

#36 feat: ensure strings always truncated
  README.md
  index.js
  lib/truncate.js
  package.json
  test/truncate.js
Labels: [zube]: In Review, breaking change, enhancement

#39 feat: add sendMetricSet method
  README.md
  index.js
  lib/truncate.js
  test/basic.js
  test/lib/utils.js
  test/truncate.js
Labels: [zube]: In Progress, enhancement

#40 fix(truncate): ensure context truncate has max
  lib/truncate.js
Labels: bug
