Repository elastic/apm-nodejs-http-client, pull requests merged in 2019-09, with the labels that each got.

#77 fix: cork timer should be cleared on destroy
  index.js
Labels: [zube]: In Review, bug

#78 fix: race-condition that could leave stream in corked state
  index.js
Labels: [zube]: In Review

#79 ci(jenkins): Set GitHub notification context to apm-ci
  .ci/jobs/defaults.yml
Labels: automation, ci

#87 test: allow test/side-effects.js to be run stand-alone
  test/side-effects.js
Labels: [zube]: In Review

#86 chore(package): bump all devDependencies
  package.json
Labels: [zube]: In Review

#85 fix(package): update fast-safe-stringify to version 2.0.7
  package.json
Labels: [zube]: In Review

#84 fix(package): update end-of-stream to version 1.4.4
  package.json
Labels: [zube]: In Review

#81 chore: drop support for older versions of Node.js
  .ci/.jenkins_nodejs.yml
  .travis.yml
  package.json
  test/config.js
  test/lib/utils.js
Labels: [zube]: In Review, breaking change

#82 refactor: use new URL parser
  index.js
  test/lib/utils.js
Labels: [zube]: In Review

#83 chore(package): bump 'standard' linter to ^14.3.1
  index.js
  lib/truncate.js
  package.json
  test/basic.js
  test/config.js
  test/lib/utils.js
  test/stringify.js
Labels: [zube]: In Review
