Repository elastic/apm-nodejs-http-client, pull requests merged in 2019-11, with the labels that each got.

#97 feat(config): add serviceNodeName
  README.md
  index.js
  test/config.js
Labels: [zube]: In Review, enhancement

#100 [jjbb] check_paths_for_matches.py not required anymore
  .ci/bin/check_paths_for_matches.py
Labels: automation, ci

#101 ci: add Node.js 13 to test matrix
  .ci/.jenkins_nodejs.yml
  .travis.yml
Labels: [zube]: In Review
