Repository elastic/apm-nodejs-http-client, pull requests merged in 2019-07, with the labels that each got.

#65 ci(jenkins): enable jenkins multibranch pipeline
  .ci/.editorconfig
  .ci/.jenkins_nodejs.yml
  .ci/Jenkinsfile
  .ci/bin/check_paths_for_matches.py
  .ci/docker/docker-compose-node-test.yml
  .ci/docker/node-container/Dockerfile
  .ci/jobs/apm-nodejs-http-client-mbp.yml
  .ci/jobs/defaults.yml
  .ci/scripts/convert_tap_to_junit.sh
  .ci/scripts/docker-test.sh
  .ci/scripts/test.sh
  .gitignore
Labels: [zube]: In Review, automation

#67 ci: enable pipeline in Jenkins with a non dockerised environment
  .ci/docker/docker-compose-node-test.yml
  .ci/docker/node-container/Dockerfile
  .ci/jobs/defaults.yml
  .ci/scripts/convert_tap_to_junit.sh
  .ci/scripts/docker-test.sh
  .ci/scripts/test.sh
  .gitignore
  README.md
Labels: [zube]: In Review, automation, enhancement

#68 ci(jjbb): fix python permissions
  .ci/bin/check_paths_for_matches.py
Labels: automation, bug

#66 feat: add support for APM Agent Configuration via Kibana
  README.md
  index.js
  test/abort.js
  test/basic.js
  test/central-config.js
  test/config.js
  test/edge-cases.js
  test/k8s.js
  test/lib/utils.js
  test/side-effects.js
  test/stringify.js
  test/truncate.js
Labels: [zube]: In Review
