Repository elastic/apm-nodejs-http-client, pull requests merged in 2019-10, with the labels that each got.

#88 feat: improve writev encoding performance
  index.js
Labels: [zube]: In Review, performance

#89 ci(jenkins): run master on daily basis
  .ci/Jenkinsfile
  .ci/jobs/apm-nodejs-http-client-mbp.yml
  .ci/jobs/apm-nodejs-http-client-schedule-daily.yml
  .ci/jobs/defaults.yml
  .ci/schedule-daily.groovy
Labels: automation, ci

#95 ci(jenkins): encapsulate environment changes
  .ci/Jenkinsfile
Labels: automation, ci

#93 fix(truncate): nulls should not be treated as objects
  lib/truncate.js
  test/truncate.js
Labels: [zube]: In Review, bug
